In [2]:
import numpy as np


In [32]:
x = np.arange(10)
%timeit y = x **3

1.22 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
%%timeit
y = np.zeros(10)
for num in x:
    y = x**3

14.2 µs ± 684 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [34]:
np.sum(x)

45

In [35]:
np.add.reduce(x)

45

In [36]:
np.add.accumulate(x)


array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [39]:
x=[1,2,3]
y=[0,1,-1]
np.multiply(x,y)

array([ 0,  2, -3])

In [42]:
np.multiply.outer(x,y)

array([[ 0,  1, -1],
       [ 0,  2, -2],
       [ 0,  3, -3]])

In [43]:
sum(x)

6

In [59]:
r = np.random.random(100)
print(r.mean(),r.std(),r.min(),r.max())

0.5036122473192362 0.2899481281769253 0.011721878392868645 0.9717053599512525


In [60]:
r = np.random.normal(size=100)
print(r.mean(),r.std(),r.min(),r.max())

-0.15785354700869184 0.9500731012216278 -2.235937759216223 1.8535654268322022


In [51]:
r.mean()

0.5165175232784996

In [62]:
x = np.random.rand(3,4)
x

array([[0.80374875, 0.88516981, 0.11427823, 0.68969955],
       [0.11565347, 0.45855489, 0.19072231, 0.69596993],
       [0.34738097, 0.76786417, 0.30856326, 0.19661503]])

In [63]:
x.min(axis = 0)

array([0.11565347, 0.45855489, 0.11427823, 0.19661503])

In [64]:
x.min(axis = 1)

array([0.11427823, 0.11565347, 0.19661503])

In [86]:
def checkfinalshape(shapea, shapeb):
    a = np.ones(shapea)
    b = np.ones(shapeb)
    print(f"shape a = {a.shape},shape b = {b.shape}, shape a+b = {(a+b).shape}")
checkfinalshape((1,3),(2,))

ValueError: operands could not be broadcast together with shapes (1,3) (2,) 

In [74]:
a = np.arange(3)[:,np.newaxis]
b = np.arange(3)
print(a.shape,b.shape)
print((a+b).shape)

(3, 1) (3,)
(3, 3)


In [67]:
a+b

array([[0, 2, 4]])

# Boolean operatrions and masking

In [132]:
a = np.random.randint(10, size=(3,4))
a

array([[9, 2, 4, 3],
       [2, 0, 6, 8],
       [7, 6, 7, 5]])

In [133]:
a>5

array([[ True, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True, False]])

In [134]:
np.sum(a>5)


6

In [135]:
np.sum(a>5, axis=0)

array([2, 1, 2, 1])

In [136]:
b = (a>=3) & (a<=7)
b

array([[False, False,  True,  True],
       [False, False,  True, False],
       [ True,  True,  True,  True]])

In [137]:
b.sum(axis=1)

array([2, 1, 4])

In [138]:
a[b]

array([4, 3, 6, 7, 6, 7, 5])

In [140]:
np.max(a[b])

7

In [141]:
np.median(a[a<7])

3.5

# Fancy Indexing

In [4]:
x = np.random.randint(10, size=(3,4))
x

array([[3, 3, 4, 4],
       [4, 1, 3, 1],
       [4, 0, 5, 5]])

In [11]:
row = np.array([0,2])
col = np.array([1,2,3])
x[row]

array([[3, 3, 4, 4],
       [4, 0, 5, 5]])

In [35]:
x[[row[0],row[1]]]

array([[3, 3, 4, 4],
       [4, 0, 5, 5]])

In [12]:
x[:,col]

array([[3, 4, 4],
       [1, 3, 1],
       [0, 5, 5]])

In [13]:
row[:,np.newaxis]

array([[0],
       [2]])

In [14]:
x[row[:,np.newaxis]]

array([[[3, 3, 4, 4]],

       [[4, 0, 5, 5]]])

In [16]:
x[row[:,np.newaxis],col] #broadcasting

array([[3, 4, 4],
       [0, 5, 5]])

In [15]:
row[:,np.newaxis]*col

array([[0, 0, 0],
       [2, 4, 6]])

# Fancy indexing with masking

In [18]:
x

array([[3, 3, 4, 4],
       [4, 1, 3, 1],
       [4, 0, 5, 5]])

In [31]:
mask = np.array([0,1,0,1],dtype=bool)
#mask2 = np.array([True,False,True])
x[:,mask]

array([[3, 4],
       [1, 1],
       [0, 5]])

In [32]:
x[row[:,np.newaxis],mask]

array([[3, 4],
       [0, 5]])

In [42]:
np.random.choice(100,20)

array([63, 48, 94, 57, 31, 38, 99, 42, 51, 43, 89, 38, 68,  1, 14, 40, 75,
       41,  2, 59])

In [ ]:
np.zeros_like()
np.searchsorted()